/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cybrom.frames;
import com.cybrom.beans.*;
import com.cybrom.dao.*;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hp-pc
 */
public class BankBook extends javax.swing.JFrame {
String username, choice = "";
    /**
     * Creates new form BankBook
     */
    public BankBook() {
        initComponents();
    }
    public BankBook(String username) {
        initComponents();
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        op1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setUndecorated(true);
        getContentPane().setLayout(null);

        tb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account ID", "Account", "Tran. Date", "Amount", "User ID", "Operation"
            }
        ));
        jScrollPane1.setViewportView(tb);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 240, 630, 170);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("Create");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(10, 50, 98, 24);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("Edit");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2);
        r2.setBounds(10, 80, 98, 24);

        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("Remove");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        getContentPane().add(r3);
        r3.setBounds(10, 110, 98, 24);

        buttonGroup1.add(r4);
        r4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.setText("Find");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        getContentPane().add(r4);
        r4.setBounds(10, 140, 98, 24);

        buttonGroup1.add(r5);
        r5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        r5.setForeground(new java.awt.Color(255, 255, 255));
        r5.setText("Find All");
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });
        getContentPane().add(r5);
        r5.setBounds(10, 170, 98, 24);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("PRESS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 200, 72, 26);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOME");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 10, 70, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exp cat.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 430);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
        if(r1.isSelected())
            choice="create";
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
        if(r2.isSelected())
            choice="edit";
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
        if(r3.isSelected())
            choice = "remove";
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        // TODO add your handling code here:
        if(r4.isSelected())
            choice="find";
    }//GEN-LAST:event_r4ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
        // TODO add your handling code here:
        if(r5.isSelected())
            choice="findall";
    }//GEN-LAST:event_r5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BankBookBeans bb = new BankBookBeans();
        BankBookDAO bbd = new BankBookDAO();
        DefaultTableModel d = (DefaultTableModel) tb.getModel();
        ArrayList al = new ArrayList();
        int acid, amount, userid, yr, mon, day;
        String acc, operation, date;
        LocalDate d1, d2, ddate;
        boolean b;
        switch(choice)
        {
            case "create":
                acid = Integer.parseInt(op1.showInputDialog(this,"Please enter the Account ID"));
                acc = op1.showInputDialog(this,"Please enter the Account type (Savings/Current/NRI)");
                date = op1.showInputDialog(this,"Please enter the transaction date(YYYY-MM-DD)");
//                yr = Integer.parseInt(date.substring(0, 4));
//                mon = Integer.parseInt(date.substring(5, 7));
//                day = Integer.parseInt(date.substring(8, 10));
//                ddate = LocalDate.of(yr, mon, day);
                amount = Integer.parseInt(op1.showInputDialog(this,"Please enter the Account ID"));
                userid = Integer.parseInt(op1.showInputDialog(this,"Please enter the User ID"));
                operation = op1.showInputDialog(this,"Please enter the operation(Credit/Debit)");
                bb.setAccount(acc);
                bb.setAcid(acid);
                bb.setAmount(amount);
                bb.setOperation(operation);
                bb.setUserid(userid);
                bb.setTransaction_date(date);
                b = bbd.create(bb);
                if(b)
                    op1.showMessageDialog(this,"Record created successfully");
                else
                    op1.showMessageDialog(this,"Record couldn't be created");
                break;
            case "edit":
                acid = Integer.parseInt(op1.showInputDialog(this,"Please enter the Account ID"));
                acc = op1.showInputDialog(this,"Please enter the Account type (Savings/Current/NRI)");
                date = op1.showInputDialog(this,"Please enter the transaction date(YYYY-MM-DD)");
//                yr = Integer.parseInt(date.substring(0, 4));
//                mon = Integer.parseInt(date.substring(5, 7));
//                day = Integer.parseInt(date.substring(8, 10));
//                ddate = LocalDate.of(yr, mon, day);
                amount = Integer.parseInt(op1.showInputDialog(this,"Please enter the Account ID"));
                userid = Integer.parseInt(op1.showInputDialog(this,"Please enter the User ID"));
                operation = op1.showInputDialog(this,"Please enter the operation(Credit/Debit)");
                bb.setAccount(acc);
                bb.setAcid(acid);
                bb.setAmount(amount);
                bb.setOperation(operation);
                bb.setUserid(userid);
                bb.setTransaction_date(date);
                b = bbd.create(bb);
                if(b)
                    op1.showMessageDialog(this,"Record updated successfully");
                else
                    op1.showMessageDialog(this,"Record couldn't be updated");
                break;
            case "remove":
                acid = Integer.parseInt(op1.showInputDialog(this,"Please enter the Account ID"));
                bb.setAcid(acid);
                b = bbd.remove(bb);
                if(b)
                    op1.showMessageDialog(this,"Records deleted successfully");
                else
                    op1.showMessageDialog(this,"Records couldn't be deleted");
                break;
            case "find":
                acid = Integer.parseInt(op1.showInputDialog(this,"Please enter the account ID"));
                bb.setAcid(acid);
                al=bbd.find(bb);
                for(int i = 0; i<al.size(); i++)
                {
                    d.addRow(new Object []{al.get(i),al.get(i+1),al.get(i+2),al.get(i+3),al.get(i+4),al.get(i+5)});
                    break;
                }
                tb.setModel(d);
                break;
            case "findall":
                al = bbd.findall(bb);
                for(int i = 0; i<al.size(); i+=6)
                {
                    d.addRow(new Object []{al.get(i),al.get(i+1),al.get(i+2),al.get(i+3),al.get(i+4),al.get(i+5)});
                }
                tb.setModel(d);
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Dashboard db = new Dashboard(username);
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JOptionPane op1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
